---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

## More stuff  
More examples of different libraries, with advanced and not parametric capacity functions.The function `aov_car` is the modified version not the CAR version.

```{r}
# Using afex library
library(tidyverse)
library(rstatix)
library(afex)
library(emmeans)

chronPain <- read_csv("~/Dropbox/GitHub/ProbEstad/DataSets/ch08_all/EXA_C08_S04_01.csv", col_names = TRUE, show_col_types = FALSE)

chronPain_long <- chronPain %>%
     pivot_longer(cols = Baseline:Month6, names_to = "Time", values_to = "APhFq")

#
chronPain_long <- chronPain_long %>%
     mutate( Subject = factor(Subject), Time = factor(Time) )

ps_chronPain_aovCar <- aov_car(APhFq ~ Time + Error(Subject/Time), data = chronPain_long)
ps_chronPain_aovCar

ps_chronPain_aovCar_phoc <- emmeans(ps_chronPain_aovCar, ~Time)

#For nonparametric
nonP_chronPain <- chronPain_long %>%
  friedman_test(APhFq ~ Time|Subject)

nonP_chronPain
```
